services:
    web-app:
      container_name: web-app
      build:
        context: ./web-app
      volumes:
        - './web-app:/web-app'
        - '/web-app/node_modules'
      ports:
        - 80:3000
      environment:
        - CHOKIDAR_USEPOLLING=true